PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE question (_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, level INTEGER NOT NULL, answer TEXT NOT NULL, mistake TEXT NOT NULL, coin INTEGER NOT NULL, cate TEXT NOT NULL, pic TEXT);
INSERT INTO question VALUES(1,1,'abcd','ABCDEFGHIJKLMNOPQRST',3,'Alpha',NULL);
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" VALUES('question',1);
COMMIT;